//
// ApiResponse.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct ApiResponse: Serializable {

    public var code: Int?
    public var type: String?
    public var message: String?

    public init(code: Int?, type: String?, message: String?) {
        self.code = code
        self.type = type
        self.message = message
    }


}

