//
// LoginResponse.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct LoginResponse: Serializable {

    public var token: String?
    public var claims: [Claim]?

    public init(token: String?, claims: [Claim]?) {
        self.token = token
        self.claims = claims
    }


}

