//
// UserPostRequest.swift
//
// Generated by oneframemobile
// https://github.com/oneframemobile/networking-swagger-swift
//

import Networking
import Foundation


public struct UserPostRequest: Serializable {

    public var email: String?
    public var password: String
    public var phoneNumber: String?

    public init(email: String?, password: String, phoneNumber: String?) {
        self.email = email
        self.password = password
        self.phoneNumber = phoneNumber
    }


}

